return {}
-- {
--   "lewis6991/gitsigns.nvim",
--   opts = function(_, opts)
--     local orig_on_attach = opts.on_attach
--     opts.on_attach = function(buffer)
--       if orig_on_attach then
--         orig_on_attach(buffer)
--       end
--
--       local gs = package.loaded.gitsigns
--     end
--   end,
-- }
